In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [75]:
df = pd.read_csv('data/train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [76]:
df = df.pipe(lambda d: d.rename(columns=lambda c: str(c).lower().strip().replace(' ', '_')))
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [77]:
# EDA
target_col = 'survived'

if 'passengerid' in df.columns:
    df.drop(columns=['passengerid'], inplace=True)

if 'name' in df.columns:
    df.drop(columns=['name'], inplace=True)

df['sex'] = df['sex'].str.lower().map({'male':1,'female':0})

df.head()

,survived,pclass,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,3,1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,0,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,0,35.0,1,0,113803,53.1000,C123,S
4,0,3,1,35.0,0,0,373450,8.0500,NaN,S

In [78]:
# Missing age values
df['age'] = df['age'].fillna(df['age'].median())

In [ ]:
# Missing values in cabin column
print(df['cabin'].isna().sum() / len(df) * 100)

# Drop cabin column as it has more than 70% missing values
df.drop(columns=['cabin'], inplace=True)

In [80]:
print(df['ticket'].nunique(), df['ticket'].isna().sum(), len(df))

# Ticket feature has high ratio (22%) of duplicate values (unique=681).
df.drop(columns=['ticket'], inplace=True)

681 0 891

In [81]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare embarked
0         0       3    1  22.0      1      0   7.2500        S
1         1       1    0  38.0      1      0  71.2833        C
2         1       3    0  26.0      0      0   7.9250        S
3         1       1    0  35.0      1      0  53.1000        S
4         0       3    1  35.0      0      0   8.0500        S

In [82]:
df['embarked'].isnull().sum()

np.int64(2)

In [83]:
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)

C:\Users\SubudhiK\AppData\Local\Temp\ipykernel_19008\1964997694.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)

In [84]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

encoded = encoder.fit_transform(df[['embarked']])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(['embarked']),
    index=df.index
)

df = pd.concat([df.drop(columns=['embarked']), encoded_df], axis=1)

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked_C,embarked_Q,embarked_S
0,0,3,1,22.0,1,0,7.2500,0.0,0.0,1.0
1,1,1,0,38.0,1,0,71.2833,1.0,0.0,0.0
2,1,3,0,26.0,0,0,7.9250,0.0,0.0,1.0
3,1,1,0,35.0,1,0,53.1000,0.0,0.0,1.0
4,0,3,1,35.0,0,0,8.0500,0.0,0.0,1.0

In [85]:
scaler = StandardScaler()

scaled_values = scaler.fit_transform(
    df[['age', 'fare', 'pclass', 'sibsp', 'parch']]
)

scaled_df = pd.DataFrame(
    scaled_values,
    columns=['age', 'fare', 'pclass', 'sibsp', 'parch'],
    index=df.index
)

df[['age', 'fare', 'pclass', 'sibsp', 'parch']] = scaled_df

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked_C,embarked_Q,embarked_S
0,0,0.827377,1,-0.565736,0.432793,-0.473674,-0.502445,0.0,0.0,1.0
1,1,-1.566107,0,0.663861,0.432793,-0.473674,0.786845,1.0,0.0,0.0
2,1,0.827377,0,-0.258337,-0.474545,-0.473674,-0.488854,0.0,0.0,1.0
3,1,-1.566107,0,0.433312,0.432793,-0.473674,0.420730,0.0,0.0,1.0
4,0,0.827377,1,0.433312,-0.474545,-0.473674,-0.486337,0.0,0.0,1.0

In [86]:

X = df.drop(columns=[target_col])
y = df[target_col]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [87]:
# Logistic Regression model
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
acc_logreg = round(logreg.score(X_test, y_test) * 100, 2)
acc_logreg

81.01

In [88]:
# Support Vector Machines
from sklearn.svm import SVC

svc = SVC(C=1.0, kernel='rbf', gamma='scale')
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
acc_svc = round(svc.score(X_test, y_test) * 100, 2)
acc_svc

81.56

In [89]:
# knn model
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc_knn = round(knn.score(X_test, y_test) * 100, 2)
acc_knn

81.01

In [90]:
# Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB

gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
y_pred = gaussian.predict(X_test)
acc_gaussian = round(gaussian.score(X_test, y_test) * 100, 2)
acc_gaussian

77.09

In [91]:
# Perceptron
from sklearn.linear_model import Perceptron

perceptron = Perceptron(max_iter=1000, tol=1e-3, random_state=42)
perceptron.fit(X_train, y_train)
y_pred = perceptron.predict(X_test)
acc_perceptron = round(perceptron.score(X_test, y_test) * 100, 2)
acc_perceptron

74.86

In [92]:
# Linear SVC
from sklearn.svm import LinearSVC

linear_svc = LinearSVC(max_iter=1000, tol=1e-3, random_state=42)
linear_svc.fit(X_train, y_train)
y_pred = linear_svc.predict(X_test)
acc_linear_svc = round(linear_svc.score(X_test, y_test) * 100, 2)
acc_linear_svc

78.77

In [93]:
# Stochastic Gradient Descent
from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier(max_iter=1000, tol=1e-3, random_state=42)
sgd.fit(X_train, y_train)
y_pred = sgd.predict(X_test)
acc_sgd = round(sgd.score(X_test, y_test) * 100, 2)
acc_sgd

77.65

In [94]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=42, ccp_alpha=0.01)
decision_tree.fit(X_train, y_train)
y_pred = decision_tree.predict(X_test)
acc_decision_tree = round(decision_tree.score(X_test, y_test) * 100, 2)
acc_decision_tree

79.89

In [95]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(n_estimators=100, random_state=42, min_samples_leaf=1, max_features=0.01)
random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)
random_forest.score(X_train, y_train)
acc_random_forest = round(random_forest.score(X_test, y_test) * 100, 2)
acc_random_forest

81.01

In [98]:
models = pd.DataFrame({
    'Model': ['Support Vector Machines', 'KNN', 'Logistic Regression', 
              'Random Forest', 'Naive Bayes', 'Perceptron', 
              'Stochastic Gradient Decent', 'Linear SVC', 
              'Decision Tree'],
    'Score': [acc_svc, acc_knn, acc_logreg, 
              acc_random_forest, acc_gaussian, acc_perceptron, 
              acc_sgd, acc_linear_svc, acc_decision_tree]})
models.sort_values(by='Score', ascending=False)

                        Model  Score
0     Support Vector Machines  81.56
1                         KNN  81.01
2         Logistic Regression  81.01
3               Random Forest  81.01
8               Decision Tree  79.89
7                  Linear SVC  78.77
6  Stochastic Gradient Decent  77.65
4                 Naive Bayes  77.09
5                  Perceptron  74.86

In [ ]:
# ANN model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# Initialize the ANN
ann = Sequential()
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=10, restore_best_weights=True)

ann.add(Dense(units=32, activation='relu', input_shape=(X_train.shape[1],)))
ann.add(Dropout(0.2))
ann.add(Dense(units=16, activation='relu'))
ann.add(Dropout(0.2))
ann.add(Dense(units=8, activation='relu'))
ann.add(Dropout(0.3))
ann.add(Dense(units=1, activation='sigmoid'))
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history = ann.fit(X_train, y_train, batch_size=32, epochs=100, validation_split=0.2, callbacks=[es])
loss, acc_ann = ann.evaluate(X_test, y_test)
acc_ann = round(acc_ann * 100, 2)
acc_ann

Epoch 1/100

c:\Users\SubudhiK\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.6151 - loss: 0.6578 - val_accuracy: 0.6503 - val_loss: 0.6226
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6134 - loss: 0.6390 - val_accuracy: 0.6503 - val_loss: 0.5995
Epoch 3/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6169 - loss: 0.6275 - val_accuracy: 0.6503 - val_loss: 0.5826
Epoch 4/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6257 - loss: 0.6204 - val_accuracy: 0.6573 - val_loss: 0.5689
Epoch 5/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6239 - loss: 0.6116 - val_accuracy: 0.6853 - val_loss: 0.5565
Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6467 - loss: 0.6003 - val_accuracy: 0.6923 - val_loss: 0.5479
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6538 - loss: 0.5989 - val_accuracy: 0.7273 - val_loss: 0.5389
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6837 - loss: 0.5843 - val_accuracy: 0.7273 - val_loss: 0.5310
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6872 - loss: 0.5770 - val_accuracy: 0.7343 - val_loss: 0.5246
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7100 - loss: 0.5803 - val_accuracy: 0.7413 - val_loss: 0.5224
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7346 - loss: 0.5704 - val_accuracy: 0.7622 - val_loss: 0.5216
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7311 - loss: 0.5617 - val_accuracy: 0.7622 - val_loss: 0.5119
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7381 - loss: 0.5622 - val_accuracy: 0.7692 - val_loss: 0.5047
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7135 - loss: 0.5897 - val_accuracy: 0.7622 - val_loss: 0.5027
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7311 - loss: 0.5672 - val_accuracy: 0.7552 - val_loss: 0.5082
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7241 - loss: 0.5514 - val_accuracy: 0.7622 - val_loss: 0.4933
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7575 - loss: 0.5365 - val_accuracy: 0.7622 - val_loss: 0.4956
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7610 - loss: 0.5541 - val_accuracy: 0.7552 - val_loss: 0.4904
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7522 - loss: 0.5401 - val_accuracy: 0.7762 - val_loss: 0.4944
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7645 - loss: 0.5520 - val_accuracy: 0.7762 - val_loss: 0.4912
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7750 - loss: 0.5155 - val_accuracy: 0.7692 - val_loss: 0.4739
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7873 - loss: 0.5172 - val_accuracy: 0.7972 - val_loss: 0.4718
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7926 - loss: 0.5133 - val_accuracy: 0.7902 - val_loss: 0.4728
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7768 - loss: 0.5275 - val_accuracy: 0.7972 - val_loss: 0.4668
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7873 - loss: 0.5235 - val_accuracy: 0.7902 - val_loss: 0.4658
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7768 - loss: 0.5159 - val_accuracy: 0.7972 - val_loss: 0.4619
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7944 - loss: 0.4888 - val_accuracy: 0.7972 - val_loss: 0.4572
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7996 - loss: 0.5125 - val_accuracy: 0.7902 - val_loss: 0.4611
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7944 - loss: 0.5152 - val_accuracy: 0.7972 - val_loss: 0.4593
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7680 - loss: 0.5229 - val_accuracy: 0.7972 - val_loss: 0.4571
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7961 - loss: 0.4943 - val_accuracy: 0.7972 - val_loss: 0.4549
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8014 - loss: 0.5037 - val_accuracy: 0.7972 - val_loss: 0.4520
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7891 - loss: 0.5022 - val_accuracy: 0.8042 - val_loss: 0.4484
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8137 - loss: 0.4964 - val_accuracy: 0.7902 - val_loss: 0.4485
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7750 - loss: 0.5101 - val_accuracy: 0.7972 - val_loss: 0.4459
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7979 - loss: 0.4880 - val_accuracy: 0.7902 - val_loss: 0.4445
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8014 - loss: 0.4859 - val_accuracy: 0.7902 - val_loss: 0.4439
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8067 - loss: 0.4874 - val_accuracy: 0.7832 - val_loss: 0.4518
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7996 - loss: 0.4934 - val_accuracy: 0.7762 - val_loss: 0.4543
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8049 - loss: 0.4821 - val_accuracy: 0.7972 - val_loss: 0.4478
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7944 - loss: 0.4748 - val_accuracy: 0.7972 - val_loss: 0.4462
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7891 - loss: 0.4887 - val_accuracy: 0.8042 - val_loss: 0.4387
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8120 - loss: 0.4806 - val_accuracy: 0.8182 - val_loss: 0.4358
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8102 - loss: 0.4732 - val_accuracy: 0.8182 - val_loss: 0.4355
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8032 - loss: 0.4735 - val_accuracy: 0.8322 - val_loss: 0.4327
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8049 - loss: 0.4823 - val_accuracy: 0.8112 - val_loss: 0.4320
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8014 - loss: 0.4641 - val_accuracy: 0.7972 - val_loss: 0.4328
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7961 - loss: 0.5042 - val_accuracy: 0.8112 - val_loss: 0.4330
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8049 - loss: 0.4752 - val_accuracy: 0.8112 - val_loss: 0.4325
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8049 - loss: 0.4916 - val_accuracy: 0.8182 - val_loss: 0.4288
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8014 - loss: 0.4775 - val_accuracy: 0.7902 - val_loss: 0.4367
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8190 - loss: 0.4556 - val_accuracy: 0.8112 - val_loss: 0.4300
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7909 - loss: 0.4929 - val_accuracy: 0.8112 - val_loss: 0.4305
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8102 - loss: 0.4721 - val_accuracy: 0.8112 - val_loss: 0.4243
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8172 - loss: 0.4772 - val_accuracy: 0.8112 - val_loss: 0.4250
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8243 - loss: 0.4654 - val_accuracy: 0.8182 - val_loss: 0.4213
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7926 - loss: 0.4781 - val_accuracy: 0.8112 - val_loss: 0.4228
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7909 - loss: 0.4783 - val_accuracy: 0.8112 - val_loss: 0.4219
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8172 - loss: 0.4555 - val_accuracy: 0.8182 - val_loss: 0.4149
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8120 - loss: 0.4567 - val_accuracy: 0.8112 - val_loss: 0.4153
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8190 - loss: 0.4680 - val_accuracy: 0.8392 - val_loss: 0.4098
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8190 - loss: 0.4652 - val_accuracy: 0.8182 - val_loss: 0.4128
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4663 - val_accuracy: 0.8182 - val_loss: 0.4147
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8032 - loss: 0.4433 - val_accuracy: 0.8322 - val_loss: 0.4097
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8120 - loss: 0.4565 - val_accuracy: 0.8112 - val_loss: 0.4124
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8260 - loss: 0.4482 - val_accuracy: 0.8322 - val_loss: 0.4112
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8137 - loss: 0.4595 - val_accuracy: 0.8182 - val_loss: 0.4152
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8102 - loss: 0.4548 - val_accuracy: 0.8322 - val_loss: 0.4106
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8014 - loss: 0.4616 - val_accuracy: 0.8252 - val_loss: 0.4118
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8155 - loss: 0.4486 - val_accuracy: 0.8182 - val_loss: 0.4111
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8172 - loss: 0.4471 - val_accuracy: 0.8322 - val_loss: 0.4120
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4427 - val_accuracy: 0.8252 - val_loss: 0.4071
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8102 - loss: 0.4272 - val_accuracy: 0.8322 - val_loss: 0.4041
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8207 - loss: 0.4428 - val_accuracy: 0.8322 - val_loss: 0.4049
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8172 - loss: 0.4348 - val_accuracy: 0.8252 - val_loss: 0.4090
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4437 - val_accuracy: 0.8252 - val_loss: 0.4085
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8190 - loss: 0.4324 - val_accuracy: 0.8462 - val_loss: 0.4060
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8383 - loss: 0.4318 - val_accuracy: 0.8322 - val_loss: 0.4094
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8260 - loss: 0.4540 - val_accuracy: 0.8322 - val_loss: 0.4117
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8330 - loss: 0.4285 - val_accuracy: 0.8322 - val_loss: 0.4122
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8243 - loss: 0.4385 - val_accuracy: 0.8322 - val_loss: 0.4095
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8243 - loss: 0.4201 - val_accuracy: 0.8322 - val_loss: 0.4084
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8049 - loss: 0.4727 - val_accuracy: 0.8392 - val_loss: 0.4108
Epoch 83: early stopping
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8324 - loss: 0.4139

83.24

In [105]:
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score

y_pred_prob = ann.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_pred_prob))

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[[95 10]
 [20 54]]
              precision    recall  f1-score   support

           0       0.83      0.90      0.86       105
           1       0.84      0.73      0.78        74

    accuracy                           0.83       179
   macro avg       0.83      0.82      0.82       179
weighted avg       0.83      0.83      0.83       179

ROC-AUC: 0.8903474903474903

In [107]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from scikeras.wrappers import KerasClassifier
import numpy as np

def create_model():
    ann = Sequential()
    ann.add(Dense(32, activation='relu', input_shape=(X.shape[1],)))
    ann.add(Dropout(0.2))
    ann.add(Dense(16, activation='relu'))
    ann.add(Dropout(0.2))
    ann.add(Dense(8, activation='relu'))
    ann.add(Dropout(0.3))
    ann.add(Dense(1, activation='sigmoid'))
    ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return ann

model = KerasClassifier(model=create_model, epochs=80, batch_size=32, verbose=0)

kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(model, X, y, cv=kfold, scoring='accuracy')

print("CV Accuracy scores:", scores)
print("Mean CV Accuracy:", scores.mean())
print("Std Dev:", scores.std())

c:\Users\SubudhiK\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\SubudhiK\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000002A7F8D88E00> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

c:\Users\SubudhiK\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000002A7F8EBF420> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

c:\Users\SubudhiK\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\SubudhiK\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

CV Accuracy scores: [0.84357542 0.80337079 0.80898876 0.8258427  0.8258427 ]
Mean CV Accuracy: 0.8215240725629277
Std Dev: 0.014214349517335101